# Gradle Specifications
org.gradle.jvmargs=-Xms256M -Xmx2G
org.gradle.daemon=false

# General Specifications
mc_version=1.12.2
mod_version=1.0.1
forge_version=14.23.5.2855
mod_group=com.integral.littlevecx
mod_id=littlevecx
mod_name=LittleVecX
mod_archives_name=LittleVecX1.12.2
mod_author=ArchangelD
mod_icon=logo.png
mod_description=LittleVecX — это продвинутое дополнение для LittleTiles, добавляющее промышленные инструменты, расширенные анимации, лифты, удобные рецепты и дополнительные утилиты для создания сложной архитектуры, механизмов и декоративных конструкций.
mod_credits=Built on top of LittleTiles and CreativeCore.

